name: demoemanom
favicon: null
layout_spectrum: 0
typography_spectrum: 0.84879
title: The demo site
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1c00ff'
    - '#ffffff'
    - '#ffdbff'
    - '#a170cf'
    - '#c79de7'
  brandStrength: 0.125
  lightness: 0.5625
  saturation: 0.25
  rhythmicContrast: 0.5
purpose: []
