name: demoemanom
favicon: null
layout_spectrum: 0.78901
typography_spectrum: 0.84879
title: The demo site
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#dfddde'
    - '#bac0be'
    - '#86807c'
    - '#6f5e54'
    - '#6d3d28'
  brandStrength: 0.4375
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.25
purpose: []
