name: demoemanom
favicon: null
layout_spectrum: 1
typography_spectrum: 0.49482
title: The demo site
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#ff7f00'
    - '#a69189'
    - '#433e3f'
    - '#1b0704'
  brandStrength: 0.5
  lightness: 0.25
  saturation: 0.625
  rhythmicContrast: 0.75
purpose: []
